### ISSUE TITLE
Message: array_unshift() expects parameter 1 to be array, string given in  libraries/Theme.php:1226

### ISSUE THREAD

**Issue by redaxhu** [CodeIgniterSkeleton/skeleton#1]
### Steps to reproduce the issue

At login screen
/skeleton/public/login

### Actual result

A PHP Error was encountered
Severity: Warning

Message: array_unshift() expects parameter 1 to be array, string given

Filename: libraries/Theme.php

Line Number: 1226

Backtrace:

File: /home/redax/git/skeleton2/src/skeleton/libraries/Theme.php
Line: 1226
Function: array_unshift

File: /home/redax/git/skeleton2/src/skeleton/libraries/Theme.php
Line: 1162
Function: _guess_title

File: /home/redax/git/skeleton2/public/content/plugins/social-meta-tags/social-meta-tags.php
Line: 99
Function: get_title

File: /home/redax/git/skeleton2/src/skeleton/third_party/Plugins/Plugins.php
Line: 540
Function: init

File: /home/redax/git/skeleton2/src/skeleton/third_party/Plugins/Plugins.php
Line: 949
Function: do_action

File: /home/redax/git/skeleton2/src/skeleton/libraries/Kbcore/drivers/Kbcore_plugins.php
Line: 418
Function: do_action

File: /home/redax/git/skeleton2/src/skeleton/libraries/Kbcore/Kbcore.php
Line: 154
Function: load_plugins

File: /home/redax/git/skeleton2/src/skeleton/core/KB_Loader.php
Line: 396
Function: library

File: /home/redax/git/skeleton2/src/skeleton/core/KB_Controller.php
Line: 93
Function: driver

File: /home/redax/git/skeleton2/src/skeleton/modules/users/controllers/Users.php
Line: 73
Function: __construct

File: /home/redax/git/skeleton2/public/index.php
Line: 336
Function: require_once

### System information (as much as possible)

Tell us more about your system specs.

### Additional comments

if we add this test to the top of the function _guess_title() it is solved:
    private function _guess_title()
    {
        $temp_title = ('index' !== $this->method) ? $this->method : array();

+++        if( !is_array($temp_title)  ) return;
        // Controller has same module's name or module is null?
        if (null === $this->module)

**Comment by bkader** [comment]
Thanks @redaxhu for reporting this. This was an issue with v1, it was fixed on v2 but I will fix it right away.
See [v1](https://github.com/CodeIgniterSkeleton/skeleton/blob/8bce06340d2bdf2fe217266b8c616182cb2dbcae/src/skeleton/libraries/Theme.php#L1212) and [v2](https://github.com/CodeIgniterSkeleton/skeleton/blob/a1617eab4de1cb3f34ca93427e489316ef47ed27/skeleton/libraries/Theme.php#L1284).
